export const GET_COMPLAINTS = 'GET_COMPLAINTS';
export const GET_COMPLAINT = 'GET_COMPLAINT';
export const ADD_COMPLAINT = 'ADD_COMPLAINT';
export const UPDATE_COMPLAINT = 'UPDATE_COMPLAINT';
export const COMPLAINTS_LOADING = 'COMPLAINTS_LOADING';

export const SET_USER_ROLE = "SET_USER_ROLE";
export const USER_LOADING = 'USER_LOADING';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';

export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
